version: '3'
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "3333:8080"
    volumes:
      - "/app/node_modules"
      - "./:/app"
    